export const products = [
  // nike
  {
    id: 1,
    title: "Nike Air Max 90",
    price: 120,
    description: "Classic Nike sneakers with Air Max technology.",
    categories: ["nike"],
    image: "nike_air_max_90.jpg",
  },
  {
    id: 2,
    title: "Nike Air Max 90",
    price: 120,
    description: "Classic Nike sneakers with Air Max technology.",
    categories: ["nike"],
    image: "nike_air_max_90.jpg",
  },
  {
    id: 3,
    title: "Nike Air Max 90",
    price: 120,
    description: "Classic Nike sneakers with Air Max technology.",
    categories: ["nike"],
    image: "nike_air_max_90.jpg",
  },
  {
    id: 4,
    title: "Nike Air Max 90",
    price: 120,
    description: "Classic Nike sneakers with Air Max technology.",
    categories: ["nike"],
    image: "nike_air_max_90.jpg",
  },
  {
    id: 5,
    title: "Nike Air Max 90",
    price: 120,
    description: "Classic Nike sneakers with Air Max technology.",
    categories: ["nike"],
    image: "nike_air_max_90.jpg",
  },
  //   adidas
  {
    id: 6,
    title: "Adidas Ultraboost",
    price: 160,
    description: "High-performance running shoes with Boost cushioning.",
    categories: ["adidas"],
    image: "adidas_ultraboost.jpg",
  },
  {
    id: 7,
    title: "Adidas Ultraboost",
    price: 160,
    description: "High-performance running shoes with Boost cushioning.",
    categories: ["adidas"],
    image: "adidas_ultraboost.jpg",
  },
  {
    id: 8,
    title: "Adidas Ultraboost",
    price: 160,
    description: "High-performance running shoes with Boost cushioning.",
    categories: ["adidas"],
    image: "adidas_ultraboost.jpg",
  },
  {
    id: 9,
    title: "Adidas Ultraboost",
    price: 160,
    description: "High-performance running shoes with Boost cushioning.",
    categories: ["adidas"],
    image: "adidas_ultraboost.jpg",
  },
  {
    id: 10,
    title: "Adidas Ultraboost",
    price: 160,
    description: "High-performance running shoes with Boost cushioning.",
    categories: ["adidas"],
    image: "adidas_ultraboost.jpg",
  },

  // yeezy
  {
    id: 11,
    title: "Yeezy Boost 350",
    price: 220,
    description: "Kanye West's signature sneaker design.",
    categories: ["yeezy"],
    image: "yeezy_boost_350.jpg",
  },
  {
    id: 12,
    title: "Yeezy Boost 350",
    price: 220,
    description: "Kanye West's signature sneaker design.",
    categories: ["yeezy"],
    image: "yeezy_boost_350.jpg",
  },
  {
    id: 13,
    title: "Yeezy Boost 350",
    price: 220,
    description: "Kanye West's signature sneaker design.",
    categories: ["yeezy"],
    image: "yeezy_boost_350.jpg",
  },
  {
    id: 14,
    title: "Yeezy Boost 350",
    price: 220,
    description: "Kanye West's signature sneaker design.",
    categories: ["yeezy"],
    image: "yeezy_boost_350.jpg",
  },
  {
    id: 15,
    title: "Yeezy Boost 350",
    price: 220,
    description: "Kanye West's signature sneaker design.",
    categories: ["yeezy"],
    image: "yeezy_boost_350.jpg",
  },

  //   newBalance
  {
    id: 16,
    title: "New Balance 574",
    price: 80,
    description: "Classic New Balance sneakers with ENCAP cushioning.",
    categories: ["newbalance"],
    image: "new_balance_574.jpg",
  },
  {
    id: 17,
    title: "New Balance 574",
    price: 80,
    description: "Classic New Balance sneakers with ENCAP cushioning.",
    categories: ["newbalance"],
    image: "new_balance_574.jpg",
  },
  {
    id: 18,
    title: "New Balance 574",
    price: 80,
    description: "Classic New Balance sneakers with ENCAP cushioning.",
    categories: ["newbalance"],
    image: "new_balance_574.jpg",
  },

  {
    id: 19,
    title: "New Balance 574",
    price: 80,
    description: "Classic New Balance sneakers with ENCAP cushioning.",
    categories: ["newbalance"],
    image: "new_balance_574.jpg",
  },
  {
    id: 20,
    title: "New Balance 574",
    price: 80,
    description: "Classic New Balance sneakers with ENCAP cushioning.",
    categories: ["newbalance"],
    image: "new_balance_574.jpg",
  },

  //   converse
  {
    id: 21,
    title: "Converse Chuck Taylor All Star",
    price: 50,
    description: "Iconic canvas sneakers suitable for any occasion.",
    categories: ["converse"],
    image: "converse_chuck_taylor.jpg",
  },
  {
    id: 22,
    title: "Converse Chuck Taylor All Star",
    price: 50,
    description: "Iconic canvas sneakers suitable for any occasion.",
    categories: ["converse"],
    image: "converse_chuck_taylor.jpg",
  },
  {
    id: 23,
    title: "Converse Chuck Taylor All Star",
    price: 50,
    description: "Iconic canvas sneakers suitable for any occasion.",
    categories: ["converse"],
    image: "converse_chuck_taylor.jpg",
  },
  {
    id: 24,
    title: "Converse Chuck Taylor All Star",
    price: 50,
    description: "Iconic canvas sneakers suitable for any occasion.",
    categories: ["converse"],
    image: "converse_chuck_taylor.jpg",
  },
  {
    id: 25,
    title: "Converse Chuck Taylor All Star",
    price: 50,
    description: "Iconic canvas sneakers suitable for any occasion.",
    categories: ["converse"],
    image: "converse_chuck_taylor.jpg",
  },
];
